import { FileText, Scissors, Minimize2, Image, ImagePlus, RotateCw, ArrowUpDown, Droplets, Lock, Unlock, FileType, FileCode, ScanSearch, Highlighter, EyeOff } from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  category: "core" | "convert" | "advanced";
  color: string;
  seoTitle: string;
  seoContent: string;
}

export const tools: Tool[] = [
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one document",
    icon: FileText,
    category: "core",
    color: "bg-primary",
    seoTitle: "Merge PDF Files Online For Free | Fylora",
    seoContent: "Merging your PDF files has never been easier or more secure. Fylora's Merge PDF tool allows you to combine multiple PDF documents into a single, cohesive file entirely within your web browser. Perfect for students organizing research papers, professionals compiling monthly reports, or anyone looking to declutter their digital workspace. Unlike other online document tools, Fylora processes your files client-side. This means your private files never touch our servers, ensuring 100% privacy and lightning-fast speeds. Start merging your PDFs instantly, without annoying ads or forced sign-ups.",
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Extract pages or split into separate files",
    icon: Scissors,
    category: "core",
    color: "bg-primary",
    seoTitle: "Split PDF Pages Online & Extract Files | Fylora",
    seoContent: "Extract exactly the pages you need with Fylora's Free Split PDF tool. Whether you are dealing with a massive ebook, a lengthy legal contract, or a grouped invoice file, splitting your document allows you to focus on what matters. Our browser-based processing guarantees that your sensitive documents remain strictly on your device. Separate pages into individual files or extract a specific page range instantly. Fylora provides a fast, secure, and ad-free experience, making PDF splitting seamless for students and businesses alike.",
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size while maintaining quality",
    icon: Minimize2,
    category: "core",
    color: "bg-primary",
    seoTitle: "Compress PDF Online - Reduce File Size Free | Fylora",
    seoContent: "Struggling with email attachment limits? Fylora's Compress PDF tool significantly reduces the file size of your documents while preserving crucial visual quality. By utilizing advanced client-side compression algorithms, your files are optimized completely within your browser, ensuring complete privacy. No uploads, no waiting in queues, and no exposed data. Choose between balanced or maximum compression levels depending on your needs. Perfect for compressing heavy portfolios, scanned documents, and image-rich presentations quickly and securely.",
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to Image",
    description: "Convert PDF pages to high-quality images",
    icon: Image,
    category: "convert",
    color: "bg-primary",
    seoTitle: "Convert PDF to JPG/PNG Images Free | Fylora",
    seoContent: "Transform your PDF documents into high-quality image files instantly with Fylora. Our PDF to JPG/PNG converter is designed for creators, designers, and professionals who need to extract visual assets or share documents as images. Everything happens securely on your own device—no data is ever uploaded to external servers. This unparalleled commitment to privacy means you can securely convert confidential briefings, design mockups, and financial statements to image formats without a second thought. Fast, free, and perfectly ad-free.",
  },
  {
    id: "jpg-to-pdf",
    name: "Image to PDF",
    description: "Create PDF from images",
    icon: ImagePlus,
    category: "convert",
    color: "bg-primary",
    seoTitle: "Convert JPG to PDF - Image to PDF Converter | Fylora",
    seoContent: "Easily combine multiple images into a single, professional PDF document using Fylora's Image to PDF tool. Whether you are archiving receipts, building a photography portfolio, or compiling scanned notes, this utility handles the task securely and instantly in your browser. Because Fylora runs client-side, your personal photographs and sensitive image data are completely safe and never uploaded. Organize and convert your JPG and PNG files into a clean PDF format ready for printing or emailing without dealing with intrusive ads.",
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate pages in any direction",
    icon: RotateCw,
    category: "core",
    color: "bg-primary",
    seoTitle: "Rotate PDF Pages Online Free | Fylora",
    seoContent: "Scanned your document upside down? Fylora's Rotate PDF tool provides a quick, secure way to fix document orientation directly within your browser. Select specific pages or rotate the entire document 90, 180, or 270 degrees clockwise. Since our PDF tools operate via WebAssembly locally on your device, you avoid slow upload times and data privacy risks. Rotate legal documents, academic papers, and private invoices confidently, knowing that your files remain 100% private.",
  },
  {
    id: "reorder-pdf",
    name: "Reorder Pages",
    description: "Drag and drop to rearrange pages",
    icon: ArrowUpDown,
    category: "core",
    color: "bg-primary",
    seoTitle: "Reorder PDF Pages Instantly Online | Fylora",
    seoContent: "Take control of your document structure with Fylora's Reorder PDF Pages utility. Quickly organize the flow of your report or presentation by dragging and dropping pages into the correct sequence. There's no need to download clunky desktop software; our browser-based tool allows you to rearrange pages securely and instantly. Ideal for fixing collation errors or restructuring imported records, our entirely client-side processing guarantees that your organized files stay perfectly private.",
  },
  {
    id: "watermark-pdf",
    name: "Add Watermark",
    description: "Add text or image watermarks",
    icon: Droplets,
    category: "core",
    color: "bg-primary",
    seoTitle: "Add Watermark to PDF Free | Protect Documents | Fylora",
    seoContent: "Protect your intellectual property effortlessly by stamping your documents using Fylora's PDF Watermark tool. Add customized text like 'CONFIDENTIAL' or 'DRAFT' across your pages to prevent unauthorized distribution. Because Fylora focuses intensely on data security through zero-upload client-side processing, you can confidently watermark your most proprietary business proposals and sensitive drafts without risking interception on cloud servers. Add watermarks securely, accurately, and free of charge.",
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    description: "Add password protection to your PDF",
    icon: Lock,
    category: "core",
    color: "bg-primary",
    seoTitle: "Password Protect PDF Documents Free | Fylora",
    seoContent: "Secure your high-stakes documents before emailing them using Fylora's Protect PDF feature. By applying rugged encryption algorithms and a strong password, you guarantee that only intended recipients possess the keys to your files. The best part? The encryption happens instantly on your own computer. Because your unencrypted files never leave your device, Fylora eliminates the risk of cloud breaches, making it the safest way to lock tax returns, medical records, and legal drafts.",
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password from protected PDFs",
    icon: Unlock,
    category: "core",
    color: "bg-primary",
    seoTitle: "Unlock PDF - Remove PDF Password Online | Fylora",
    seoContent: "Gain full access to documents you already own by stripping away cumbersome passwords with Fylora's Unlock PDF tool. If you have the legitimate password but want to remove the encryption for easier future access, this client-side utility does it instantly. Keeping your files completely secure, the decryption process takes place within the browser, meaning your unlocked document and your password are never transmitted over the internet or saved on our servers.",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Text",
    description: "Extract plain text from PDF files",
    icon: FileType,
    category: "convert",
    color: "bg-primary",
    seoTitle: "Convert PDF to Text & Word Free | Fylora",
    seoContent: "Easily extract editable text from standard PDF documents using Fylora's rapid PDF to Text utility. Whether you need to copy-paste passages from a locked research paper or pull text from a financial report, our 100% private, browser-based extraction engine makes it instantaneous. Unlike other tools that read and store your documents remotely, Fylora processes text extraction locally on your hardware, protecting your sensitive content at all times. A reliable, ad-free alternative for content retrieval.",
  },
  {
    id: "pdf-to-md",
    name: "PDF to Markdown",
    description: "Convert PDF content to Markdown",
    icon: FileCode,
    category: "convert",
    color: "bg-primary",
    seoTitle: "Convert PDF to Markdown (MD) Format | Fylora",
    seoContent: "Developers and content creators can quickly export document content into web-ready formats using our PDF to Markdown converter. Fylora precisely extracts text and attempts to preserve semantic structure, outputting clean, highly usable .md files for GitHub readmes, blogs, and documentation sites. Enjoy completely private conversions driven entirely by your browser's processing power. No arbitrary upload limits, no wait times, and zero privacy compromises.",
  },
  {
    id: "ocr-pdf",
    name: "OCR Extract",
    description: "Extract text from scanned documents",
    icon: ScanSearch,
    category: "advanced",
    color: "bg-primary",
    seoTitle: "Free PDF OCR - Extract Text from Scans | Fylora",
    seoContent: "Turn flat, scanned images back into searchable, selectable data with Fylora's robust Optical Character Recognition (OCR) tool. Utilizing powerful client-side AI modules, Fylora inspects images within your PDF and intelligently pulls out raw text. Ideal for digitizing old physical receipts, historical documents, and printed classroom handouts. By keeping the OCR process running deeply within your local machine, we provide a uniquely privacy-first solution to data extraction.",
  },
  {
    id: "annotate-pdf",
    name: "Annotate PDF",
    description: "Add highlights, underlines, and comments",
    icon: Highlighter,
    category: "advanced",
    color: "bg-primary",
    seoTitle: "Annotate & Edit PDF Online Free | Fylora",
    seoContent: "Review documents dynamically by utilizing Fylora's secure Annotate PDF tool. Add bright highlights to critical paragraphs, underline mistakes, or drop text comments directly onto the document. This feature acts as a private, fast PDF editor designed for students studying course materials or professionals marking up contract revisions. Since all rendering and editing are performed actively on your device, your private intellectual property is never exposed to external networks.",
  },
  {
    id: "redact-pdf",
    name: "Redact PDF",
    description: "Permanently remove sensitive content",
    icon: EyeOff,
    category: "advanced",
    color: "bg-primary",
    seoTitle: "Redact PDF - Blackout Sensitive Information | Fylora",
    seoContent: "Permanently blackout classified or personally identifiable information using Fylora's rigorous Redact PDF tool. Drawing black boxes over text in basic editors often leaves the underlying text searchable—Fylora ensures the data is thoroughly and irreversibly stripped from the file code. Because this operation requires handling highly sensitive details like Social Security Numbers or banking info, our strictly client-side processing is the only truly safe way to sanitize your documents online.",
  },
];

export const getToolById = (id: string) => tools.find(t => t.id === id);
